homeassistant:
  # Customization file
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
   - type: trusted_networks
     trusted_networks:
        - 127.0.0.1
  #external_url: "https://hass.continually-evolving.net:8123"
  #internal_url: "https://hass.continually-evolving.net:8123"

auth:
# Discover some devices automatically
#discovery:
#zeroconf:
#ssdp:

system_health:

frontend:
  themes: !include_dir_merge_named themes/

config:
person:
map:
energy:

recorder:
  db_url: !secret mysql_connection
  auto_purge: true
  purge_keep_days: 7
  commit_interval: 10

http:
  ip_ban_enabled: true
  ssl_certificate: /config/ssl/fullchain.pem
  ssl_key: /config/ssl/privkey.pem

#zwave:
  #usb_path: /dev/ttyACM0
  #network_key: !secret zwave_network_key
  #autoheal: false

prometheus:
  component_config_glob:
    sensor.*_volume:
      override_metric: water_volume
    sensor.*_area:
      override_metric: room_area

device_tracker:
#  - platform: unifi
#    host: !secret unifi_host
#    verify_ssl: False
#    username: !secret unifi_username
#    password: !secret unifi_password

#  - platform: google_maps
#    username: !secret google_maps_username

#  - platform: icloud
#    username: !secret icloud_username
#    password: !secret icloud_password

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_control_panel_code
    # Don't require the code to arm the alarm
    code_arm_required: false
    # Arm again after triggering
    disarm_after_trigger: false
    # Delay from arming and becoming armed, eg. to leave the house.
    arming_time: 120
    # Allow time to disarm the alarm before it triggers, eg. when arriving home
    delay_time: 60
    # Amount of time the alarm is triggered for
    trigger_time: 600
    disarmed:
      # Ensure the alarm can never be directly triggered when disarmed
      trigger_time: 0
    armed_home:
      # Leave no delay between arming -> armed
      arming_time: 0
      # Leave no delay between pending -> triggered
      delay_time: 0

timer:
  # Used to repeat notifications that the alarm needs to be disarmed
  alarm_pending:
    duration: "00:00:10"

mobile_app:

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 100
    icon: mdi:home-modern
  - name: School
    latitude: !secret school_latitude
    longitude: !secret school_longitude
    radius: 150
    icon: mdi:school
  - name: Dancing
    latitude: !secret dancing_latitude
    longitude: !secret dancing_longitude
    radius: 100
    icon: mdi:school
  - name: Tor Magnus Work
    latitude: !secret tor_magnus_work_latitude
    longitude: !secret tor_magnus_work_longitude
    radius: 120
    icon: mdi:account-hard-hat
  - name: Lande Work
    latitude: !secret lande_work_latitude
    longitude: !secret lande_work_longitude
    radius: 120
    icon: mdi:account-hard-hat
  - name: Cabin
    latitude: !secret cabin_latitude
    longitude: !secret cabin_longitude
    radius: 1000
    icon: mdi:image-filter-hdr

proximity:
  vacation:
    zone: home
    devices: 
      - device_tracker.vog_l29
      - device_tracker.lande_phone
      - device_tracker.sm_g930f
    tolerance: 50000
    unit_of_measurement: m
  tmc_home:
    zone: home
    devices:
      - device_tracker.vog_l29
    tolerance: 100
    unit_of_measurement: m
  lande_home:
    zone: home
    devices:
      - device_tracker.lande_phone
    tolerance: 100
    unit_of_measurement: m
  ingrid_home:
    zone: home
    devices:
      - device_tracker.sm_g930f
    tolerance: 100
    unit_of_measurement: m

remote:
  - platform: xiaomi_miio
    name: "Ingrid remote"
    host: !secret xiaomi_ir_2_ip
    token: !secret xiaomi_ir_2_token
    commands:
      power:
        command:
          - 'raw:nE5mswlk0mk0mEsmoBBABnNJzMJZNpgAOsxm8zAUIAwgEDAH8AeAPDmwAazGbTcAjpqCCYCEABlMZsBX4DXgpUAPwKvgD+DbQMnzGbBvsAG8xm04AI8Aj5ZMIAA='
      volume_up:
        command:
          - 'raw:nE5mswlk0mgAhTWaABlNgDCnMwlk2mAA6zGbzMBQgDCAQMAfwB4A0IDx5jNpuARYCrADnMZsCeQBEgV+ARoHCA9FMZuC+YQZgKGDPQEDgJ4Bx4ECAomAgc2nABBBzEAR4BHgESCUUwgA'
      volume_down:
        command:
          - 'raw:nE5mswlk0mgAhTWaABlNgDCnMwlk2mAA6zGbzMBQgDCAQMAfwB4AjMDggBzmM2A1IEk5jNwGfAQQAwpjNpuAR4BHgEMEgwItgDoAu4D/gJuAu4JCBsmAGUxm04AIIAMgEeAI8AjZhAA='
      mute:
        command:
          - 'raw:nE5mswlk0mgAhTWaABlNgDCnMwlk2mAA6zGbzMBQgDCAQMAf5qA2c3AHYDggBzmM2A1IEkwCFAVMFYwGTm4GRgIFMZsBmYBHgEeAQwSjgi+AhAPDgDoBh4JMBMpOACCDnMANgEIAI8AiphAA'
      light_onoff:
        command:
          - 'raw:nMwmMwlk0mk2mEsms5ADKZgD0AmYAZzgBfgB/AHqYzaagEPNAEfAI8AhgYSmM2BiMBqwf8Bn8Adwl6A4UBDwCPAI8IjwboAZiYQA'
  - platform: xiaomi_miio
    name: "TV Room remote"
    host: !secret xiaomi_ir_ip
    token: !secret xiaomi_ir_token
    commands:
      power:
        command:
          - 'pronto:0000 006d 0022 0003 00a9 00a8 0015 003f 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0015 0015 003f 0015 003f 0015 003f 0015 003f 0015 003f 0015 003f 0015 0702 00a9 00a8 0015 0015 0015 0e6e'
      hdmi1:
        command:
          - 'pronto:0000 006D 0000 0022 00AB 00AB 0015 003F 0015 003F 0015 003F 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003F 0015 003F 0015 003F 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003F 0015 0015 0015 0015 0015 003F 0015 0015 0015 003F 0015 003F 0015 003F 0015 0015 0015 003F 0015 003F 0015 0015 0015 003F 0015 0015 0015 0015 0015 0015 0015 071C'
      hdmi2:
        command:
          - 'pronto:0000 006D 0000 0022 00AC 00AB 0015 0041 0015 0041 0015 0041 0015 0016 0015 0016 0015 0016 0015 0016 0015 0016 0015 0041 0015 0041 0015 0041 0015 0016 0015 0016 0015 0016 0015 0016 0015 0016 0015 0016 0015 0041 0015 0041 0015 0041 0015 0041 0015 0041 0015 0016 0015 0041 0015 0041 0015 0016 0015 0016 0015 0016 0015 0016 0015 0016 0015 0041 0015 0016 0015 0689'
      hdmi3:
        command:
          - 'pronto:0000 006D 0000 0022 00AC 00AC 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0015 0015 0015 0015 0015 0015 0015 0015 0040 0015 0040 0015 0040 0015 0015 0015 0040 0015 0040 0015 0040 0015 0040 0015 0015 0015 0015 0015 0689'
      hdmi4:
        command:
          - 'pronto:0000 006D 0000 0022 00AC 00AB 0015 0041 0015 0041 0015 0041 0015 0016 0015 0016 0015 0016 0015 0016 0015 0016 0015 0041 0015 0041 0015 0041 0015 0016 0015 0016 0015 0016 0015 0016 0015 0016 0015 0041 0015 0016 0015 0041 0015 0016 0015 0016 0015 0016 0015 0041 0015 0041 0015 0016 0015 0041 0015 0016 0015 0041 0015 0041 0015 0041 0015 0016 0015 0016 0015 0689'
      volume_up:
        command:
          - 'pronto:0000 006d 0022 0003 00a9 00a8 0015 003f 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 003f 0015 003f 0015 003f 0015 003f 0015 0702 00a9 00a8 0015 0015 0015 0e6e'
      volume_down:
        command:
          - 'pronto:0000 006d 0022 0003 00a9 00a8 0015 003f 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 003f 0015 0015 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 0015 0015 003f 0015 003f 0015 003f 0015 003f 0015 0702 00a9 00a8 0015 0015 0015 0e6e'
      mute:
        command:
          - 'pronto:0000 006c 0022 0003 00ab 00aa 0015 003f 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 0015 003f 0015 0015 0015 003f 0015 003f 0015 0015 0015 0015 0015 0015 0015 003f 0015 0015 0015 003f 0015 0015 0015 0015 0015 003f 0015 003f 0015 003f 0015 0714 00ab 00aa 0015 0015 0015 0e91'


camera:
  - platform: zoneminder

stream:

# Enables support for tracking state changes over time
history:

logger:
  default: warning
  logs:
    homeassistant.util.yaml.loader: warning
    homeassistant.components.automation: info
    homeassistant.components.switch: warning
    homeassistant.components.light: info 
    homeassistant.components.zwave: info
    homeassistant.components.lock: info
    homeassistant.components.python_script: info
    homeassistant.components.http.ban: warning
    homeassistant.components.prometheus: error
    homeassistant.components.netatmo: info
    homeassistant.components.automation.webhook_test: debug

# View all events in a logbook
logbook:
  exclude:
    domains:
      - sensor

# Track the sun
sun:


#cast:
#  media_player:
#    # Google Home
#    - host: 192.168.0.123
#    - host: 192.168.0.124
#    - host: 192.168.0.125
#    - host: 192.168.0.126
#    # Google Chromecast
#    - host: 192.168.0.201
#    - host: 192.168.0.202
#    - host: 192.168.0.203
#    - host: 192.168.0.204

sonos:
  media_player:
    hosts:
      - 192.168.0.211
      - 192.168.0.212

vacuum:
    - platform: xiaomi_miio
      host: !secret xiaomi_roborock_ip
      token: !secret xiaomi_roborock_token

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    time_memory: 3600

input_number:
input_select:
  home_state:
    name: Home State
    icon: mdi:home-circle
    options:
      - Home
      - Away
      - Vacation

  vacuum_area:
    name: Choose an area to clean
    options:
      - Select Area
      - island
      - table
      - hallway

  tv_input:
    name: TV input source
    options:
      - Chromecast
      - Nintendo


input_datetime:
  alarm_time_tor:
    name: Alarm Time
    has_date: false
    has_time: true
  alarm_time_lande:
    name: Alarm Time
    has_date: false
    has_time: true
  alarm_time_ingrid:
    name: Alarm Time
    has_date: false
    has_time: true


notify:
  - name: mail
    platform: smtp
    sender: !secret notify_mail_sender
    sender_name: My Home Assistant
    recipient: !secret notify_mail_recipient
    server: !secret notify_mail_server
    port: 25
  - name: html5
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
  - name: family_notification
    platform: group
    services:
      - service: mobile_app_tor_magnus_p30_pro
      - service: mobile_app_ingrids_phone
      - service: mobile_app_sm_g973f


google_assistant:
  project_id: api-project-511361644410
  service_account: !include google_assistant.json
  report_state: true
  expose_by_default: false
  entity_config:
    light.neopixel_light:
      name: Guest Bedroom Mood Light
      expose: true
      room: Guest Bedroom
    light.guest_bedroom_dimmer_current_value:
      name: Guest Bedroom Ceiling
      expose: true
      room: Guest Bedroom
    light.ceiling:
      name: Master Bathroom Ceiling
      expose: true
      room: Master Bathroom
    light.nook_table:
      name: Nook Side Table
      expose: true
      room: Nook
    light.nook_mood_current_value:
      name: Nook Mood Light
      expose: true
      room: Nook
    light.nook:
      name: Nook Standing Lamp
      expose: true
      room: Nook
    light.dining_room_rail_2:
      name: Office Ceiling
      expose: true
      room: Office Area
    light.bookshelf:
      name: Office Bookshelf
      expose: true
      room: Office Area
    light.downstairs_hallway_pendant_current_value:
      name: Downstairs Hallway Ceiling
      expose: true
      room: Downstairs Hallway
    light.changing_room_ceiling_light_current_value:
      name: Changing Room Ceiling
      expose: true
      room: Changing Room
    light.wardrobes:
      name: Changing Room Wardrobes
      expose: true
      room: Changing Room
    light.cabinets:
      name: Dining Room Cabinets
      expose: true
      room: Dining Room
    light.sofa:
      name: Dining Room Sofa
      expose: true
      room: Dining Room
    light.serving_table:
      name: Dining Room Serving Table
      expose: true
      room: Dining Room
    light.dining_room_rail_1:
      name: Dining Room Dining Table
      expose: true
      room: Dining Room
    light.dining_room_rail_3:
      name: Dining Room Stairs
      expose: true
      room: Dining Room
    light.kitchen_hallway_ceiling_lights_current_value:
      name: Kitchen Hallway 
      expose: true
      room: Kitchen
    light.kitchen_table_ceiling_lamp_current_value:
      name: Kitchen Table 
      expose: true
      room: Kitchen
    light.kitchen_bench_ceiling_lights_current_value:
      name: Kitchen Bench
      expose: true
      room: Kitchen
    light.training_room_ceiling:
      name: Training Room Ceiling
      expose: true
      room: Training Room
    light.lamp:
      name: Training Room Lamp
      expose: true
      room: Training Room
    light.ingrid_bedroom_bed_light:
      name: Ingrid Bedroom Bed Light
      expose: true
      room: Ingrid Bedroom
    light.ingrid_bedroom_ceiling_light_current_value:
      name: Ingrid Bedroom Ceiling
      expose: true
      room: Ingrid Bedroom
    light.family_bathroom_dimmer_current_value:
      name: Family Bathroom Ceiling
      expose: true
      room: Family Bathroom
    light.laundry_dimmer_current_value:
      name: Laundry Ceiling
      expose: true
      room: Laundry
    light.laundry_bench_light:
      name: Laundry Bench
      expose: true
      room: Laundry
    light.hallway_toilet_ceiling_dimmer_current_value:
      name: Hallway Toilet Ceiling
      expose: true
      room: Entrance Toilet
    light.dressing_table:
      name: Master Bedroom Dressing Table
      expose: true
      room: Master Bedroom
    light.bedside_lamp_dimmer_current_value:
      name: Master Bedroom Bedside Table
      expose: true
      room: Master Bedroom
    light.bedroom_tv_backlight:
      name: Ingrid Bedroom TV
      expose: true
      room: Ingrid Bedroom
    light.tv_room_table_lamp:
      name: TV Room Table
      expose: true
      room: TV Room
    light.hallway_area_current_value:
      name: TV Room Hallway
      expose: true
      room: TV Room
    light.sofa_area_current_value:
      name: TV Room Sofa
      expose: true
      room: TV Room
    light.tv_area_current_value:
      name: TV Room TV Wall
      expose: true
      room: TV Room
    light.entrance_wardrobes:
      name: Entrance Hallway Wardrobes
      expose: true
      room: Entrance Hallway
    light.entrance_hallway_ceiling_lights_current_value:
      name: Entrance Hallway Ceiling 
      expose: true
      room: Entrance Hallway
    light.balcony_outside_light_current_value:
      name: Outside Balcony
      expose: true
      room: Outside
    light.terrace:
      name: Outside Terrace
      expose: true
      room: Outside
    light.porch:
      name: Outside Porch
      expose: true
      room: Outside
    media_player.tv_room_tv:
      name: TV Room TV
      expose: true
      room: TV room
    input_boolean.sleep_state_tor:
      name: tor magnus sleeping
      expose: true
      room: Master bedroom
    input_boolean.sleep_state_lande:
      name: lande sleeping
      expose: true
      room: Master bedroom
    input_boolean.dinner_time:
      name: dinner time
      expose: true
    input_boolean.sleep_state_ingrid:
      name: ingrid sleeping
      expose: true
      room: Ingrid bedroom
 
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

min_renovasjon:
  street_name: "Holmsens vei"
  house_no: "29B"
  street_code: "6350"
  county_id: "3030"
  date_format: "None"

netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret

  #octoprint:
  #host: !secret octoprint_host
  #api_key: !secret octoprint_key
  #name: "Prusa i3 MK2S"
  #bed: true
  #number_of_tools: 1

utility_meter:
  water_yearly:
    source: sensor.water_consumption_volume
    cycle: yearly
    tariffs:
      - fixed
  water_monthly:
    source: sensor.water_consumption_volume
    cycle: monthly
    tariffs:
      - fixed
  water_daily:
    source: sensor.water_consumption_volume
    cycle: daily
    tariffs:
      - fixed
  electricity_yearly:
    source: sensor.accumulated_consumption_holmsens_vei_29b
    cycle: yearly
    tariffs:
      - fixed
  electricity_monthly:
    source: sensor.accumulated_consumption_holmsens_vei_29b
    cycle: monthly
    tariffs:
      - fixed
  electricity_daily:
    source: sensor.accumulated_consumption_holmsens_vei_29b
    cycle: daily
    tariffs:
      - fixed
  electricity_cost_yearly:
    source: sensor.accumulated_cost_holmsens_vei_29b
    cycle: yearly
    tariffs:
      - fixed
  electricity_cost_monthly:
    source: sensor.accumulated_cost_holmsens_vei_29b
    cycle: monthly
    tariffs:
      - fixed
  electricity_cost_daily:
    source: sensor.accumulated_cost_holmsens_vei_29b
    cycle: daily
    tariffs:
      - fixed

zoneminder:
  - host: !secret zm_host
    ssl: true
    username: !secret zm_username
    password: !secret zm_password
    path_zms: /zm/cgi-bin/nph-zms

input_boolean: !include input_boolean.yaml
switch: !include switch.yaml
group: !include groups.yaml
binary_sensor: !include binary-sensor.yaml
sensor: !include sensor.yaml
automation: !include automations.yaml
script: !include scripts.yaml
#alert: !include alerts.yaml
fan: !include fans.yaml
light: !include light.yaml
