- platform: template
  fans:
    humidity_fan:
      friendly_name: "Humidity extraction fan"
      value_template: "{{ states('light.house_ventilation_dimmer_current_value') }}"
      percentage_template: "{{ (state_attr('light.house_ventilation_dimmer_current_value','brightness') |int /255*100) |int }}"
      turn_on:
        service: light.turn_on
        entity_id: light.house_ventilation_dimmer_current_value
      turn_off:
        service: light.turn_off
        entity_id: light.house_ventilation_dimmer_current_value
      set_percentage:
        service: light.turn_on
        entity_id: light.house_ventilation_dimmer_current_value
        data:
          brightness_pct: "{{ percentage }}"
      speed_count: 255
