- platform: switch
  name: Porch
  entity_id: switch.entrance_outside_light
- platform: switch
  name: Training room ceiling
  entity_id: switch.training_room_light_current_value
- platform: switch
  name: Terrace
  entity_id: switch.terrace_outside_light_current_value
- platform: switch
  name: Wardrobes
  entity_id: switch.dressing_room_wardrobes_current_value
- platform: switch
  name: TV room table lamp
  entity_id: switch.tv_room_lamp

- platform: group
  name: Kitchen
  entities:
    - light.kitchen_bench_ceiling_lights_current_value
    - light.kitchen_table_ceiling_lamp_current_value
    - light.kitchen_hallway_ceiling_lights_current_value
- platform: group
  name: TV Lounge
  entities:
    - light.tv_area_current_value
    - light.sofa_area_current_value
    - light.hallway_area_current_value
- platform: group
  name: Entrance
  entities:
    - light.entrance_hallway_ceiling_lights_current_value
    - light.entrance_wardrobes
- platform: group
  name: Dining room
  entities:
    - light.nook
    - light.nook_mood_current_value
    - light.nook_table
    - light.bookshelf
    - light.dining_room_rail_1
    - light.dining_room_rail_2
    - light.dining_room_rail_3
    - light.serving_table
    - light.sofa
    - light.cabinets
- platform: group
  name: Master bedroom
  entities:
    - light.bedroom_tv_backlight_current_value
    - light.bedside_lamp_dimmer_current_value
    - light.dressing_table
    - light.wardrobes
    - light.changing_room_ceiling_light_current_value

