- platform: zoneminder
  monitored_conditions:
    - all
    - month
    - week
    - day
    - hour

#- platform: nordpool
#  currency: 'NOK'
#  region: 'Oslo'
#  name: "Elspot kWh"

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: min_max
  type: mean
  name: "Water heater"
  entity_ids:
    - sensor.water_heater_bottom_temperature
    - sensor.water_heater_middle_temperature
    - sensor.water_heater_top_temperature

- platform: template
  sensors:
    average_humidity:
      friendly_name: "Average house humidity"
      unit_of_measurement: "%"
      icon_template: mdi:water-percent
      value_template: >
        {% if states.sensor.netatmo_home_dining_room_humidity.state and states.sensor.family_bathroom_multisensor_humidity.state and states.sensor.laundry_multisensor_humidity.state %}
          {% set totalvalue = states('sensor.netatmo_home_dining_room_humidity')|float + states('sensor.family_bathroom_multisensor_humidity')|float + states('sensor.laundry_multisensor_humidity')|float %}
          {% set totalcount = 3 %}
          {% if totalcount > 0 %}
            {% set totalaverage = totalvalue / totalcount %}
          {% else %}
            {% set totalaverage = 40 %}
          {% endif %}
          {{totalaverage|round(1)}}
        {% else %}
          40
        {% endif %}

    divergence_humidity:
      friendly_name: "Divergence from average house humidity"
      unit_of_measurement: "%"
      icon_template: mdi:water-percent
      value_template: >
        {% if float(states.sensor.netatmo_home_dining_room_humidity.state) and states.sensor.family_bathroom_multisensor_humidity.state and states.sensor.laundry_multisensor_humidity.state %}
          {% set average =  states('sensor.netatmo_home_dining_room_humidity') | float + states('input_number.humifity_threshold_modifier') | float %}
          {% set family  = (states('sensor.family_bathroom_multisensor_humidity') | float - average) - 2 %}
          {% set laundry = (states('sensor.laundry_multisensor_humidity') | float - average) - 4 %}
          {{[family,laundry]|max|round(1)}}
        {% else %}
          0
        {% endif %}

    sunrise:
      friendly_name: "Sunrise at"
      icon_template: mdi:weather-sunset-up
      value_template: "{{ as_timestamp(state_attr('sun.sun', 'next_rising')) | timestamp_custom('%H:%M') }}"
    sunset:
      friendly_name: "Sunset at"
      icon_template: mdi:weather-sunset-down
      value_template: "{{ as_timestamp(state_attr('sun.sun', 'next_setting')) | timestamp_custom('%H:%M') }}"
    price_level:
      friendly_name: "Electricity price level"
      icon_template: mdi:cash
      value_template: "{{ state_attr('sensor.electricity_price_holmsens_vei_29b', 'price_level') }}"

- platform: mqtt
  name: water_consumption_volume
  unit_of_measurement: "m³"
  state_topic: "wmbusmeters/58079516"
  value_template: "{{value_json.total_m3}}"
- platform: mqtt
  name: water_internal_temperature
  unit_of_measurement: "°C"
  state_topic: "wmbusmeters/58079516"
  value_template: "{{value_json.flow_temperature_c}}"
- platform: mqtt
  name: water_external_temperature
  unit_of_measurement: "°C"
  state_topic: "wmbusmeters/58079516"
  value_template: "{{value_json.external_temperature_c}}"

- platform: systemmonitor
  resources:
    type: disk_use_percent
    arg: /


- platform: min_renovasjon
  fraction_id:
    - 1
    - 2

